server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  profiles:
    active: "prod"
  main:
    banner-mode: off

logging:
  pattern:
    console: "%d [a:%X{accountId},c:%X{bot},r:%X{requestId}] %5p [%8c] - %m %n"
    file: "%d [a:%X{accountId},c:%X{bot},r:%X{requestId}] %5p [%8c] - %m %n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: "main.%d.%i.log.gz"
  file:
    name: app.main.log
  level:
    "com.justai": debug
    "org.springframework": warn

bot:
  accessToken: ${JAICP_API_TOKEN}
  helloImageUrl: "https://media.giphy.com/media/ICOgUNjpvO0PC/source.gif"
  byeImageUrl: "https://media.giphy.com/media/EE185t7OeMbTy/source.gif"
